name: listencare
description: "A speech to text app for hearing impaired people"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  path_provider: ^2.1.0
  permission_handler: ^10.4.3
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.1  # Primary speech recognition package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/vosk_models/vosk-model-en/vosk-model-small-en-us-0.15.zip
    - assets/vosk_models/vosk-model-ur/vosk-model-small-en-in-0.4.zip
flutter_icons:
  android: true
  image_path: "/home/haseeb-raza/Desktop/Listencare/listencare/assets/images/STT (1).png"